[project]
name = "chemspider"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "feapder[render]>=1.9.2",
    "html5lib>=1.1",
    "pandas>=2.2.3",
    "setuptools>=78.1.0",
]
