@echo off
python grid-draw.py H
python grid-draw.py He
python grid-draw.py Li
python grid-draw.py Be
python grid-draw.py B
python grid-draw.py C
python grid-draw.py N
python grid-draw.py O
python grid-draw.py F
python grid-draw.py Ne
python grid-draw.py Na
python grid-draw.py Mg
python grid-draw.py Al
python grid-draw.py Si
python grid-draw.py P
python grid-draw.py S
python grid-draw.py Cl
python grid-draw.py Ar
python grid-draw.py K
python grid-draw.py Ca
python grid-draw.py Sc
python grid-draw.py Ti
python grid-draw.py V
python grid-draw.py Cr
python grid-draw.py Mn
python grid-draw.py Fe
python grid-draw.py Co
python grid-draw.py Ni
python grid-draw.py Cu
python grid-draw.py Zn
python grid-draw.py Ga
python grid-draw.py Ge
python grid-draw.py As
python grid-draw.py Se
python grid-draw.py Br
python grid-draw.py Kr
python grid-draw.py Rb
python grid-draw.py Sr
python grid-draw.py Y
python grid-draw.py Zr
python grid-draw.py Nb
python grid-draw.py Mo
python grid-draw.py Tc
python grid-draw.py Ru
python grid-draw.py Rh
python grid-draw.py Pd
python grid-draw.py Ag
python grid-draw.py Cd
python grid-draw.py In
python grid-draw.py Sn
python grid-draw.py Sb
python grid-draw.py Te
python grid-draw.py I
python grid-draw.py Xe
python grid-draw.py Cs
python grid-draw.py Ba
python grid-draw.py La
python grid-draw.py Ce
python grid-draw.py Pr
python grid-draw.py Nd
python grid-draw.py Pm
python grid-draw.py Sm
python grid-draw.py Eu
python grid-draw.py Gd
python grid-draw.py Tb
python grid-draw.py Dy
python grid-draw.py Ho
python grid-draw.py Er
python grid-draw.py Tm
python grid-draw.py Yb
python grid-draw.py Lu
python grid-draw.py Hf
python grid-draw.py Ta
python grid-draw.py W
python grid-draw.py Re
python grid-draw.py Os
python grid-draw.py Ir
python grid-draw.py Pt
python grid-draw.py Au
python grid-draw.py Hg
python grid-draw.py Tl
python grid-draw.py Pb
python grid-draw.py Bi
python grid-draw.py Po
python grid-draw.py At
python grid-draw.py Rn
python grid-draw.py Fr
python grid-draw.py Ra
python grid-draw.py Ac
python grid-draw.py Th
python grid-draw.py Pa
python grid-draw.py U
python grid-draw.py Np
python grid-draw.py Pu
python grid-draw.py Am
python grid-draw.py Cm
python grid-draw.py Bk
python grid-draw.py Cf
python grid-draw.py Es
python grid-draw.py Fm
python grid-draw.py Md
python grid-draw.py No
python grid-draw.py Lr